services:
  notebook:
    build: .
    image: uoc-python-datascience
    container_name: uoc-python-datascience
    volumes:
      - ./python_1:/app/work/python_1
      - ./python_2:/app/work/python_2
      - ./util:/app/work/util
    command: sh -c "conda run -n uoc \
      jupyter lab \
        --ip=* \
        --port 8888 \
        --no-browser \
        --allow-root \
        --notebook-dir=/app/work \
        --preferred-dir=/app/work \
        --NotebookApp.token=''"
    ports:
      - 8888:8888
    restart: always