name: uoc
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - biopython
  - chardet
  - flake8
  - geoplotlib
  - ipykernel
  - jupyterlab
  - matplotlib
  - networkx
  - numpy
  - pandas
  - pip
  - pycodestyle
  - pyglet
  - python=3.11
  - python-louvain
  - requests
  - scikit-learn
  - scipy
  - scrapy
  - seaborn
  - tweepy
  - pip:
      - line-profiler
      - pycodestyle-magic
